# Copyright (c) the IW4x authors (see the AUTHORS file).
# SPDX-License-Identifier: GPL-3.0-only

import libs = libcompanion%lib{companion}

# The hooking engine is only built for Windows targets.
#
./: exe{driver}: include = ($cxx.target.class == 'windows')

exe{driver}: {hxx ixx txx cxx}{**} $libs testscript
