# Copyright (c) the IW4x authors (see the AUTHORS file).
# SPDX-License-Identifier: GPL-3.0-only

intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.

./: lib{companion}: libul{companion}: \
  {hxx ixx txx cxx}{** -**.test... -version} \
  hxx{version} $impl_libs $intf_libs

# Unit tests.
#
exe{*.test}:
{
  test = true
  install = false
}

for t: cxx{**.test...}
{
  d = $directory($t)
  n = $name($t)...

  ./: $d/exe{$n}: $t $d/{hxx ixx txx}{+$n} $d/testscript{+$n}
  $d/exe{$n}: libul{companion}: bin.whole = false
}

hxx{version}: in{version} $src_root/manifest

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root"

obja{*}: cxx.poptions += -DLIBCOMPANION_STATIC_BUILD
objs{*}: cxx.poptions += -DLIBCOMPANION_SHARED_BUILD

# Export options.
#
lib{companion}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
  cxx.export.libs = $intf_libs
}

liba{companion}: cxx.export.poptions += -DLIBCOMPANION_STATIC
libs{companion}: cxx.export.poptions += -DLIBCOMPANION_SHARED

# For pre-releases use the complete version to make sure they cannot
# be used in place of another pre-release or the final version. See
# the version module for details on the version.* variable values.
#
if $version.pre_release
  lib{companion}: bin.lib.version = "-$version.project_id"
else
  lib{companion}: bin.lib.version = "-$version.major.$version.minor"

# Install into the libcompanion/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/libcompanion/
  install.subdirs = true
}
